"""Small wrapper around Khalti KPG-2 Web Checkout APIs."""
import httpx

from app.core.config import KHALTI_SECRET_KEY, KHALTI_BASE_URL

INITIATE_PATH = "/api/v2/epayment/initiate/"
LOOKUP_PATH = "/api/v2/epayment/lookup/"


class KhaltiError(Exception):
    def __init__(self, message: str, detail: str | None = None):
        super().__init__(message)
        self.detail = detail


def _auth_headers() -> dict[str, str]:
    if not KHALTI_SECRET_KEY:
        raise KhaltiError(
            "Khalti secret key is not configured.",
            "Set KHALTI_SECRET_KEY in backend/.env. For sandbox, use the live_secret_key generated by test-admin.khalti.com.",
        )
    return {
        "Authorization": f"Key {KHALTI_SECRET_KEY}",
        "Content-Type": "application/json",
    }


async def initiate_payment(
    *,
    amount_npr: float,
    purchase_order_id: str,
    purchase_order_name: str,
    return_url: str,
    website_url: str,
    customer_name: str | None = None,
    customer_email: str | None = None,
) -> dict:
    payload = {
        "return_url": return_url,
        "website_url": website_url,
        "amount": int(round(amount_npr * 100)),
        "purchase_order_id": purchase_order_id,
        "purchase_order_name": purchase_order_name,
    }
    customer_info = {}
    if customer_name:
        customer_info["name"] = customer_name
    if customer_email:
        customer_info["email"] = customer_email
    if customer_info:
        payload["customer_info"] = customer_info

    try:
        headers = _auth_headers()
        async with httpx.AsyncClient(timeout=20, follow_redirects=True) as client:
            resp = await client.post(
                f"{KHALTI_BASE_URL}{INITIATE_PATH}",
                headers=headers,
                json=payload,
            )
    except httpx.HTTPError as exc:
        raise KhaltiError("Could not connect to Khalti.", str(exc)) from exc

    if resp.status_code >= 400:
        # Khalti returns {detail: "Invalid token.", status_code: 401}
        # for an invalid/missing merchant auth key.
        try:
            data = resp.json()
            detail = data.get("detail") or resp.text
        except ValueError:
            detail = resp.text
        raise KhaltiError(
            f"Khalti initiate failed ({resp.status_code})",
            detail=detail,
        )

    try:
        return resp.json()
    except ValueError as exc:
        raise KhaltiError("Khalti returned an invalid response.", resp.text) from exc


async def lookup_payment(pidx: str) -> dict:
    try:
        headers = _auth_headers()
        async with httpx.AsyncClient(timeout=20, follow_redirects=True) as client:
            resp = await client.post(
                f"{KHALTI_BASE_URL}{LOOKUP_PATH}",
                headers=headers,
                json={"pidx": pidx},
            )
    except httpx.HTTPError as exc:
        raise KhaltiError("Could not connect to Khalti.", str(exc)) from exc

    if resp.status_code >= 400:
        try:
            data = resp.json()
            detail = data.get("detail") or resp.text
        except ValueError:
            detail = resp.text
        raise KhaltiError(
            f"Khalti lookup failed ({resp.status_code})",
            detail=detail,
        )

    try:
        return resp.json()
    except ValueError as exc:
        raise KhaltiError("Khalti returned an invalid lookup response.", resp.text) from exc
